spring:
  datasource:
    url: jdbc:mysql://localhost:3306/universidad?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
  
logging:
  level:
    es.iesjandula: INFO
  file:
    name: C:\logs\holaMundo.log
    max-size: 1MB
    max-history: 10