package es.iesjandula.Universidad.models.id;

import java.io.Serializable;

import es.iesjandula.Universidad.models.Alumno;
import es.iesjandula.Universidad.models.Asignatura;
import es.iesjandula.Universidad.models.Curso;
import jakarta.persistence.Embeddable;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

@Embeddable
public class MatriculaId implements Serializable
{
	/**
	 * Autogenerated SerialVersion
	 */
	private static final long serialVersionUID = -3766148353780976576L;

	@ManyToOne
    @JoinColumn(name = "id_asignatura", referencedColumnName = "id")
	private Asignatura asignatura;
	
	@ManyToOne
	@JoinColumn(name = "id_alumno", referencedColumnName = "id")
	private Alumno alumno;
	
	@ManyToOne
	@JoinColumn(name = "id_curso", referencedColumnName = "id")
	private Curso curso;
}
